Implement read jobType
kube-burner/kube-burner pull request #577
Opened 2024-01-16 14:32 UTC by riuvshyn

## Type of change

Attempt to address https://github.com/kube-burner/kube-burner/issues/575

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [x] Documentation Update

## Description

Adds new `jobType: read` which can be used to simulate load of GET requests 

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

2024-01-19 12:02 UTC, rsevilla87 commented on pkg/burner/read.go
> +		log.Infof("Job %s: %d iterations", jobConfig.Name, jobConfig.JobIterations)
I think is better to take this message outside the loop

2024-01-19 12:09 UTC, rsevilla87 commented on pkg/burner/read.go
> +	var wg sync.WaitGroup
A workgroup is not required here, the rate limiter already takes care of limiting the number of requests in parallel

2024-01-19 12:13 UTC, rsevilla87 requested changes
This feature is quite cool, simple but effective. Now I understand your desire of running jobs in parallel...

However I have some doubts, when the number of objects is high, that will span as many goroutines as the number of objects listed.

I wonder if we can limit the number of concurrent goroutines to QPS to prevent potential issues. (just realized that same issue can happen in delete jobs)

Also, can you a update tests to include this new feature?

2024-01-19 15:35 UTC, riuvshyn commented on pkg/burner/read.go
> +		log.Infof("Job %s: %d iterations", jobConfig.Name, jobConfig.JobIterations)
absolutely, missed that bit.

2024-01-19 15:50 UTC, riuvshyn commented on pkg/burner/read.go
> +	var wg sync.WaitGroup
oh, very nice!
done.

2024-01-22 08:53 UTC, riuvshyn commented
@rsevilla87 I was thinking about problem with high amount of objects spawning many goroutines, limiting amount of concurrent goroutines to QPS probably is not very good idea because based on my use cases I have not that many objects defined in my job while in some jobs I am tempting to set quite high QPS to produce significant load which I think is not unique use case for kube-burner.
I am not very concerned with creating goroutines for every object as I can't imagine sane use-case with hundreds of objects being involved, while setting up QPS to hundreds or even thousands makes alot of sense to me.

2024-01-22 09:06 UTC, riuvshyn commented on pkg/burner/read.go
> +		log.Infof("Job %s: %d iterations", jobConfig.Name, jobConfig.JobIterations)
done

2024-01-25 01:25 UTC, rsevilla87 commented on pkg/burner/read.go
> +	var wg sync.WaitGroup
My bad, we need a waitGroup to wait for goroutines to finish before moving forward to the next iteration. sorry about the confusion, I think the initial code was missing the statement wg.Wait()

2024-01-25 01:30 UTC, rsevilla87 commented
> @rsevilla87 I was thinking about problem with high amount of objects spawning many goroutines, limiting amount of concurrent goroutines to QPS probably is not very good idea because based on my use cases I have not that many objects defined in my job while in some jobs I am tempting to set quite high QPS to produce significant load which I think is not unique use case for kube-burner. I am not very concerned with creating goroutines for every object as I can't imagine sane use-case with hundreds of objects being involved, while setting up QPS to hundreds or even thousands makes alot of sense to me.

ok, makes sense, let's give it a try, we can always update and improve it in the future. Can you add a simple test case to https://github.com/kube-burner/kube-burner/blob/main/test/test-k8s.bats

Thanks!

2024-01-25 16:01 UTC, riuvshyn commented
@riuvshyn I've added simple read test case seems it is passing on CI, I was unable to run it locally because I don't have required local infra.

2024-01-25 20:00 UTC, rsevilla87 commented
> @rsevilla87 I've added simple read test case seems it is passing on CI, I was unable to run it locally because I don't have required local infra.

Great!, thank you very much!

2024-01-25 20:00 UTC, rsevilla87 approved these changes
lgtm!

2024-01-25 20:01 UTC, merged