[WIP] get addresses for job iteration object
kube-burner/kube-burner pull request #608
Opened 2024-03-07 10:32 UTC by venkataanil

GetIPAddress renders a string with IP addresses for the object template from the list of input addresses based on iteration number and number of addresses requested per object

2024-03-14 14:26 UTC, vishnuchalla commented
Looks good to me. Requires signed commit I guess.

2024-03-14 14:38 UTC, rsevilla87 commented on pkg/util/template.go
> +		fmt.Println("Iteration %s addressesPerIteration %s", Iteration, addressesPerIteration)
Don't use Println

2024-03-14 14:40 UTC, rsevilla87 commented on pkg/util/template.go
> +	funcMap["GetIPAddress"] = func(eipAddresses string, Iteration int, addressesPerIteration int) string {
What are you trying to achieve with this function?

2024-03-18 10:14 UTC, venkataanil commented on pkg/util/template.go
> +	funcMap["GetIPAddress"] = func(eipAddresses string, Iteration int, addressesPerIteration int) string {
I have created an RFE for this https://github.com/kube-burner/kube-burner-ocp/issues/32

egress ip object, which is part of job need list of ip addresses. For example 10.0.0.2 and 10.0.0.3 in the below case.

> apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
name: egressip-obj-0-1
spec:
egressIPs:
- 10.0.0.2
- 10.0.0.3

GetIPAddress() function is called from the template while rendering. Inputs are -
**eipAddresses:**  all avaialable IP addresses kube-burner-ocp has provided . Example "10.0.0.2 10.0.0.3 10.0.0.4 10.0.0.5 10.0.0.6 10.0.0.7 10.0.0.8 10.0.0.9 10.0.0.10"
**Iteration:** Iteration cout, example 0
**addrPerIteration:** Number of addresses needed by object, for example 2

> apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egressip-obj-{{.Iteration}}-{{.Replica}}
spec:
  egressIPs:
  {{range (splitList " " (GetIPAddress .eipAddresses .Iteration .addrPerIteration))}}
  - {{.}}
  {{end}}

Similarly deployment-client.yml also calls this function to get same IP addresses what the eip object got, for verfication

> apiVersion: v1
kind: Pod
spec:
containers:
…
image: quay.io/cloud-bulldozer/curl:latest
readinessProbe:
exec:
command:
- /bin/sh
- -c
- curl -s http://${SERVER_HOST}:${SERVER_PORT} | grep -qE '10.0.0.2|10.0.0.3'


Template -
https://github.com/kube-burner/kube-burner-ocp/pull/28/files#diff-8343c793121c8537ec152195e9befb0587f431ef6be2d2be3c89c18845981e0c 

> kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-{{.Replica}}
spec:
spec:
      containers:
      - name: client-app
        image: quay.io/cloud-bulldozer/curl:latest
        command: ["sleep", "inf"]
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        env:
            - "/bin/sh"
            - "-c"
            {{- $eips := (splitList " " (GetIPAddress .eipAddresses .Iteration .addrPerIteration) | join "|") }}
            - "curl -s http://${SERVER_HOST}:${SERVER_PORT} | grep -qE '{{$eips}}'"

2024-03-19 08:35 UTC, rsevilla87 commented on pkg/util/template.go
> +	        iteration := Iteration
remove this line

2024-05-31 18:53 UTC, vishnuchalla commented on pkg/util/template.go
> +	        iteration := Iteration
@venkataanil as raul suggested, can you remove that line as it seems not required.

2024-05-31 18:53 UTC, vishnuchalla requested changes
.

2024-06-03 05:03 UTC, venkataanil commented on pkg/util/template.go
> +	        iteration := Iteration
sure

2024-06-03 15:45 UTC, vishnuchalla approved these changes
lgtm

2024-06-03 15:45 UTC, merged