Enhancing waitoptions to work with lablels, custom conditions & read …
kube-burner/kube-burner pull request #670
Opened 2024-07-22 23:23 UTC by vishnuchalla

…jobs

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

2024-07-23 09:14 UTC, Mangaal commented
In Create Job I can see that It will look for any kind with the set label in the ns specified objectTemplate , 

let's say I have deployed the ArgoCD application in argocd ns but the child resource like pods, deployment can be created at any namespace. I would like to wait for the child resources with the label specified in waitOptions.
 
will it be possible to remove the namespace if we specify the label selector?
something like this
waitForObjects("", waitRateLimiter)


objectTemplate
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-{{.Iteration}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mangaal/argocd-yaml
    targetRevision: HEAD
    path: argocd-1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test-{{.Iteration}}
  syncPolicy:
    automated: {}


```
kube-burner config
```
# Global configuration
global:
  gc: false
# Jobs configuration
jobs:
  - name: argocd-performance-test
    jobIterations: 2  # Create 100 namespaces and applications
    namespace: kube-burner-argocd-test
    namespacedIterations: true
    cleanup: false
    iterationsPerNamespace: 1
    waitWhenFinished: true
    objects:
      - kind: Namespace
        objectTemplate: argocd/template/namespace.yaml
        replicas: 1  # Create 100 namespaces
      - kind: Role
        objectTemplate: argocd/template/role.yaml
        replicas: 1  
      - kind: RoleBinding
        objectTemplate: argocd/template/rolebinding.yaml
        replicas: 1   
      - kind: Application
        objectTemplate: argocd/template/application.yaml
        replicas: 1  # Deploy 100 ArgoCD applications
        waitOptions:
          kind: Pod
          labelSelector: {kube-burner: argocd-performance-test}
```

2024-07-23 11:23 UTC, vishnuchalla commented
> In Create Job I can see that It will look for any kind with the set label in the ns specified objectTemplate ,
> 
> let's say I have deployed the ArgoCD application in argocd ns but the child resource like pods, deployment can be created at any namespace. I would like to wait for the child resources with the label specified in waitOptions.
> 
> will it be possible to remove the namespace if we specify the label selector? something like this waitForObjects("", waitRateLimiter)
> 
> objectTemplate
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: Application
> metadata:
>   name: app-{{.Iteration}}
>   namespace: argocd
> spec:
>   project: default
>   source:
>     repoURL: https://github.com/Mangaal/argocd-yaml
>     targetRevision: HEAD
>     path: argocd-1
>   destination:
>     server: https://kubernetes.default.svc
>     namespace: argocd-test-{{.Iteration}}
>   syncPolicy:
>     automated: {}
> ```
> 
> kube-burner config
> 
> ```
> # Global configuration
> global:
>   gc: false
> # Jobs configuration
> jobs:
>   - name: argocd-performance-test
>     jobIterations: 2  # Create 100 namespaces and applications
>     namespace: kube-burner-argocd-test
>     namespacedIterations: true
>     cleanup: false
>     iterationsPerNamespace: 1
>     waitWhenFinished: true
>     objects:
>       - kind: Namespace
>         objectTemplate: argocd/template/namespace.yaml
>         replicas: 1  # Create 100 namespaces
>       - kind: Role
>         objectTemplate: argocd/template/role.yaml
>         replicas: 1  
>       - kind: RoleBinding
>         objectTemplate: argocd/template/rolebinding.yaml
>         replicas: 1   
>       - kind: Application
>         objectTemplate: argocd/template/application.yaml
>         replicas: 1  # Deploy 100 ArgoCD applications
>         waitOptions:
>           kind: Pod
>           labelSelector: {kube-burner: argocd-performance-test}
> ```

Sure. It should work for child object now. Can you confirm?

2024-07-23 13:51 UTC, Mangaal requested changes
Update the label selector

2024-07-23 13:51 UTC, Mangaal commented on pkg/burner/waiters.go
> +			LabelSelector: labels.Set(obj.labelSelector).String(),
change to 
LabelSelector: labels.Set(obj.WaitOptions.LabelSelector).String()
since we want to wait resource with labels from WaitOptions.LabelSelector

2024-07-23 13:51 UTC, Mangaal commented on pkg/burner/waiters.go
> +			LabelSelector: labels.Set(obj.labelSelector).String(),
```suggestion
			LabelSelector: labels.Set(obj.WaitOptions.LabelSelector).String(),
```

2024-07-23 14:00 UTC, vishnuchalla commented on pkg/burner/waiters.go
> +			LabelSelector: labels.Set(obj.labelSelector).String(),
Done Thanks

2024-07-23 14:28 UTC, Mangaal commented
Hi @vishnuchalla , I have tested and it is working But I need to adjust the jobIterationDelay to some 10s, If I do not add this the job gets completed before the child resource is created.  ArgoCD takes some time to create the resources.

Thanks for working on this feature. Hopes it gets Approved.

2024-07-23 14:30 UTC, Mangaal reviewed
LGTM

2024-07-23 14:35 UTC, vishnuchalla commented
> Hi @vishnuchalla , I have tested and it is working But I need to adjust the jobIterationDelay to some 10s, If I do not add this the job gets completed before the child resource is created. ArgoCD takes some time to create the resources.
> 
> Thanks for working on this feature. Hopes it gets Approved.

This might be something very specific to ArgoCD. If the resource is not even created, there cannot be a wait on it.

2024-07-24 10:02 UTC, rsevilla87 commented on pkg/config/types.go
> +	// LabelSelector objects with this labels will be considered
```suggestion
	// LabelSelector objects with these labels will be considered
```

2024-07-24 10:06 UTC, rsevilla87 commented on pkg/burner/waiters.go
> +	obj.gvr = schema.GroupVersionResource{
Since we're passing the object now as argument, I think is not necessary to set gvr, as it was previously set in `setupDeleteJob`, `setupCreateJob`, `setupPatchJob` or `setupReadJob`

2024-07-24 10:16 UTC, rsevilla87 commented on pkg/burner/waiters.go
>  	wait.PollUntilContextTimeout(context.TODO(), 10*time.Second, maxWaitTimeout, true, func(ctx context.Context) (done bool, err error) {
Lets drop the interval period to 1s as well to be consistent with the other wait functions.
 
```suggestion
	wait.PollUntilContextTimeout(context.TODO(), time.Second, maxWaitTimeout, true, func(ctx context.Context) (done bool, err error) {
```

2024-07-24 10:17 UTC, rsevilla87 commented on pkg/config/types.go
> +	Kind string `yaml:"kind" json:"kind,omitempty"`
can you document these new parameters?

2024-07-24 11:49 UTC, vishnuchalla commented on pkg/config/types.go
> +	// LabelSelector objects with this labels will be considered
Changed as suggested.

2024-07-24 11:49 UTC, vishnuchalla commented on pkg/burner/waiters.go
> +	obj.gvr = schema.GroupVersionResource{
Changed as suggested.

2024-07-24 11:49 UTC, vishnuchalla commented on pkg/burner/waiters.go
>  	wait.PollUntilContextTimeout(context.TODO(), 10*time.Second, maxWaitTimeout, true, func(ctx context.Context) (done bool, err error) {
Changed as suggested.

2024-07-24 11:49 UTC, vishnuchalla commented on pkg/config/types.go
> +	Kind string `yaml:"kind" json:"kind,omitempty"`
Updated

2024-07-24 12:57 UTC, rsevilla87 approved these changes
Thanks for the updates @vishnuchalla , lgtm

2024-07-24 16:26 UTC, merged