Adding kube-virt support in the CI
kube-burner/kube-burner pull request #698
Opened 2024-09-18 18:21 UTC by vishnuchalla

## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

2024-09-18 18:27 UTC, vishnuchalla commented on pkg/burner/waiters.go
> +	if obj.WaitOptions.ForCondition == "" {
This was bug that was overlooked previously.

2024-09-19 08:26 UTC, rsevilla87 requested changes

2024-09-19 08:26 UTC, rsevilla87 commented on test/helpers.bash
> +  echo "Deploying kubevirt operator"
It won't work, regular aws instances doesn't support nested virt

2024-09-19 08:27 UTC, rsevilla87 commented on pkg/burner/waiters.go
> +	if obj.WaitOptions.ForCondition == "" {
please, open a different PR to address this issue 🥺

2024-09-19 12:06 UTC, vishnuchalla commented on pkg/burner/waiters.go
> +	if obj.WaitOptions.ForCondition == "" {
Done: https://github.com/kube-burner/kube-burner/pull/700

2024-09-19 12:07 UTC, vishnuchalla commented on test/helpers.bash
> +  echo "Deploying kubevirt operator"
Yes, it should work fine with every gh actions runner. I have attached an example run description. kubevirt is madatory to deploy virtualmachines.

2024-09-24 13:50 UTC, rsevilla87 commented on test/helpers.bash
> +  echo "Deploying kubevirt operator"
oh, that's cool!

2024-09-24 13:53 UTC, rsevilla87 commented on test/test-k8s.bats
> +  check_metric_value jobSummary top2PrometheusCPU prometheusRSS podLatencyMeasurement podLatencyQuantilesMeasurement alert
I think we should check for the metrics/files `vmiLatencyQuantilesMeasurement` and `vmiLatencyMeasurement`.

Tests are actually passing because there's a bug in the metric naming, which should be fixed by https://github.com/kube-burner/kube-burner/pull/699

2024-09-24 15:44 UTC, closed without merging