Adding --configmap argument back under kube-burner init sub command
kube-burner/kube-burner pull request #710
Opened 2024-10-15 02:42 UTC by smanda99

## Type of change

- [ ] Refactor
- [X] New feature
- [ ] Bug fix
- [ ] Optimization
- [X] Documentation Update

## Description
Adding --configmap argument back under kube-burner init sub command

## Related Tickets & Documents

- Related Issue # [648](https://github.com/kube-burner/kube-burner/issues/648)
- Closes #

2024-10-15 09:20 UTC, rsevilla87 requested changes
Thanks for the PR!, tests passe, seems there're still some linting issues, can you take a look? :)

2024-11-20 21:36 UTC, vishnuchalla submitted a review, later dismissed
lgtm

2025-01-02 13:34 UTC, vishnuchalla commented
@smanda99 can you resolve conflicts and update this PR?

2025-04-11 12:15 UTC, vishnuchalla approved these changes
lgtm

2025-04-11 12:47 UTC, rsevilla87 approved these changes
lgtm

2025-04-11 12:47 UTC, merged