Preload vm image
kube-burner/kube-burner pull request #757
Opened 2024-12-10 13:49 UTC by rsevilla87

## Type of change

- [x] New feature

## Description

Preload Virtual machines images

cc @jeniferh @ygalblum

2024-12-10 14:07 UTC, ygalblum requested changes

2024-12-10 14:07 UTC, ygalblum commented on pkg/burner/pre_load.go
> +type VMorVMI struct {
VM and VMI do not have the same structure. The path `.spec.template.spec` of the VirtualMachine
 and VirtualMachineInstanceReplicaSet resources equals to the `.spec` of the VirtualMachineInstance

2024-12-10 14:39 UTC, rsevilla87 commented on pkg/burner/pre_load.go
> +type VMorVMI struct {
correct, but Im reusing the same struct to unmarshal all of the those kinds, this struct defines .spec.volumes (valid for VMIs) and .spec.template.spec.volumes (valid for VMs and VMIRS)

2024-12-10 17:12 UTC, ygalblum commented on pkg/burner/pre_load.go
> +type VMorVMI struct {
Since the handling is also separate, why not create separate types (and cases in the switch)? What's the advantage of combining it to the same struct?

2025-01-02 12:04 UTC, rsevilla87 commented on pkg/burner/pre_load.go
> +type VMorVMI struct {
fixed

2025-01-02 13:49 UTC, ygalblum approved these changes
LGTM

2025-01-02 14:35 UTC, josecastillolema approved these changes

2025-01-02 14:35 UTC, merged